joint_read_state_controller:
  type: joint_state_controller/JointStateController 
  publish_rate: 100.0

front_left_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: front_left_wheel_joint

front_left_motor_wheel_joint_controller:
  type: position_controllers/JointPositionController
  joint: front_left_motor_wheel_joint

front_right_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: front_right_wheel_joint

front_right_motor_wheel_joint_controller:
  type: position_controllers/JointPositionController
  joint: front_right_motor_wheel_joint

back_left_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: back_left_wheel_joint

back_left_motor_wheel_joint_controller:
  type: position_controllers/JointPositionController
  joint: back_left_motor_wheel_joint

back_right_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: back_right_wheel_joint

back_right_motor_wheel_joint_controller:
  type: position_controllers/JointPositionController
  joint: back_right_motor_wheel_joint

omni_drive_controller:
  type: omni_drive_controller/OmniDriveController
  joint:
    front_right_wheel_joint:
        max_speed: 20.0 # rad/s
    front_left_wheel_joint:
        max_speed: 20.0 # rad/s
    back_right_wheel_joint:
        max_speed: 20.0 # rad/s
    back_left_wheel_joint:
        max_speed: 20.0 # rad/s
    front_right_motor_wheel_joint:
        min_angle: -2.8 # rads
        max_angle: 2.8
    front_left_motor_wheel_joint:
        min_angle: -2.8 # rads
        max_angle: 2.8
    back_right_motor_wheel_joint:
        min_angle: -2.8 # rads
        max_angle: 2.8
    back_left_motor_wheel_joint:
        min_angle: -2.8 # rads
        max_angle: 2.8
  max_linear: 3 # m/s
  max_angular: 0.5 # rad/s
  odom_frame: odom
  robot_base_frame: base_footprint
  odom_broadcast_tf: true
  wheel_base: 0.934
  track_width: 0.57
  wheel_diameter: 0.186
  cmd_watchdog_duration: 0.1
  odom_publish_frequency: 100

